pluginManagement {

    repositories {

        gradlePluginPortal()

        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }

    }

}


dependencyResolutionManagement {

    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {

        mavenCentral()

        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }

    }

}


rootProject.name = 'VoidTech'
