modLoader="javafml"

loaderVersion="[47,)"

license="MIT"


[[mods]]

modId="voidtech"

version="1.0.0"

displayName="VoidTech"

authors="mikuliku"

description='''
A technology mod based on void mining.
'''



[[dependencies.voidtech]]

modId="forge"

mandatory=true

versionRange="[47,)"

ordering="NONE"

side="BOTH"



[[dependencies.voidtech]]

modId="minecraft"

mandatory=true

versionRange="[1.20.1]"

ordering="NONE"

side="BOTH"
